w00: https://go.w00.io
- alias: woo,call,dial,sms,wa,whatsapp,telegram,t,w,waze
- disable: prehtml, require continue button
zto: https://zto.one
- disable: prehtml, require continue button
default: https://www.kalman.co.il
global:
- delay:1
- prehtml: "<h2>Redirecting from $0 to $1</h2>"
- require continue button: true
